version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Adjunk automatikus címkéket:
    labels:
      - dependencies
    # Opcionális: commit üzenet prefix (látvány és kereshetőség)
    commit-message:
      prefix: "chore(deps)"
    # Opcionális: egyszerre nyitott PR-ok korlátja
    open-pull-requests-limit: 3
