blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/HKati/pulse-release-gates-0.1/security/policy
    about: Please report security vulnerabilities privately via SECURITY.md.
