# tools/gh_pr_comment_triage.py
# Használat (CI): python tools/gh_pr_comment_triage.py --summary artifacts/pulse_paradox_gate_summary.json --out triage_comment.md
import argparse, json, os, sys
from pathlib import Path

TIPS = {
    "settle_time_p95_ms": "Try: enable caching, reduce batch-size, avoid heavy debug logging, precompute hot paths.",
    "downstream_error_rate": "Try: fix top recurring errors, add guard/validation, strengthen tests on failing inputs.",
    "paradox_density": "Try: review prompt/context merges, reduce stochasticity for risky paths, tighten benign transforms."
}

def num(x):
    try:
        return float(x)
    except Exception:
        return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary", required=True, help="pulse_paradox_gate_summary.json (downloaded artifact)")
    ap.add_argument("--out", default="triage_comment.md", help="Output markdown")
    args = ap.parse_args()

    summary_p = Path(args.summary)
    if not summary_p.exists():
        print(f"ERR: summary not found: {summary_p}", file=sys.stderr)
        sys.exit(2)

    data = json.loads(summary_p.read_text(encoding="utf-8"))
    decision = data.get("decision", "UNKNOWN")
    metrics = data.get("metrics", data)  # fallback: top-level
    # próbáljuk kinyerni budgeteket
    budgets = {}
    for k in ("thresholds", "budgets", "policy"):
        v = data.get(k, {})
        if isinstance(v, dict):
            for kk, vv in v.items():
                if isinstance(vv, (int, float)):
                    budgets[kk] = vv
                elif isinstance(vv, dict):
                    for kkk, vvv in vv.items():
                        if isinstance(vvv, (int, float)):
                            budgets[kkk] = vvv

    keys = ("settle_time_p95_ms", "downstream_error_rate", "paradox_density")
    rows = []
    for k in keys:
        val = num(metrics.get(k))
        bud = budgets.get(k)
        if val is None and k in data:
            val = num(data.get(k))
        line = f"- **{k}**: {val if val is not None else 'n/a'}"
        if isinstance(bud, (int, float)):
            if val is not None:
                delta = val - bud
                sign = ">" if delta > 0 else "≤"
                extra = f" (budget {bud}, Δ{delta:+.3f})"
                line = f"- **{k}**: {val} {sign} {bud}{extra}"
            else:
                line += f" (budget {bud})"
        tip = TIPS.get(k)
        if tip: line += f" — {tip}"
        rows.append(line)

    raw_decision = (str(decision) if decision is not None else "").strip()
    if raw_decision.lower().startswith("decision:"):
        raw_decision = raw_decision.split(":", 1)[1].strip()
    decision_key = raw_decision.split()[0].split("(")[0].strip().upper() if raw_decision else ""

    md = []
    md.append("<!-- pulse-triage -->")
    title = "### PULSE • Paradox Gate — Why it failed / What to try"
    if decision_key == "NORMAL":
        title = "### PULSE • Paradox Gate — Triage (shadow) / What to try"
    md.append(title)
    md.append("")
    if decision_key == "NORMAL":
        md.append("_Decision is NORMAL (shadow-only; does not gate merges). No action required._")
        md.append("")
    md.append(f"**Decision:** {raw_decision or decision_key} (shadow mode — informational only).")
    if decision_key == "NORMAL":
        md.append("")
        md.append("<details>")
        md.append("<summary>Details (metrics + what to try if this ever fails)</summary>")
        md.append("")
        md.extend(rows)
        md.append("")
        md.append("</details>")
    else:
        md.extend(rows)
    md.append("\n_This comment is auto-generated by the gate workflow triage step._\n")

    out_p = Path(args.out)
    out_p.write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"Wrote {out_p}")

    # GitHub Actions step output (optional)
    gh_out = os.getenv("GITHUB_OUTPUT")
    if gh_out:
        with open(gh_out, "a", encoding="utf-8") as f:
            f.write("triage_body<<EOF\n")
            f.write("\n".join(md) + "\n")
            f.write("EOF\n")

if __name__ == "__main__":
    main()
